name: "g1"
joint_names:
  - "left_hip_pitch_joint"
  - "left_hip_roll_joint"
  - "left_hip_yaw_joint"
  - "left_knee_joint"
  - "left_ankle_pitch_joint"
  - "left_ankle_roll_joint"
  - "right_hip_pitch_joint"
  - "right_hip_roll_joint"
  - "right_hip_yaw_joint"
  - "right_knee_joint"
  - "right_ankle_pitch_joint"
  - "right_ankle_roll_joint"
  - "waist_yaw_joint"
  - "waist_roll_joint"
  - "waist_pitch_joint"
  - "left_shoulder_pitch_joint"
  - "left_shoulder_roll_joint"
  - "left_shoulder_yaw_joint"
  - "left_elbow_joint"
  - "left_wrist_roll_joint"
  - "left_wrist_pitch_joint"
  - "left_wrist_yaw_joint"
  - "right_shoulder_pitch_joint"
  - "right_shoulder_roll_joint"
  - "right_shoulder_yaw_joint"
  - "right_elbow_joint"
  - "right_wrist_roll_joint"
  - "right_wrist_pitch_joint"
  - "right_wrist_yaw_joint"
foot_names:
  - "LL_FOOT"
  - "LR_FOOT"
comm_freq: 500
kp: 100.0
kd: 2.0
standing_cfg: [ 
  # Left leg (6 joints): hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll
  -0.05, 0.0, 0.0, 0.35, -0.3, 0.0,
  # Right leg (6 joints): hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll
  -0.05, 0.0, 0.0, 0.35, -0.3, 0.0,
  # Waist (3 joints): yaw, roll, pitch
  0.0, 0.0, 0.0,
  # Left arm (7 joints): shoulder_pitch, shoulder_roll, shoulder_yaw, elbow, wrist_roll, wrist_pitch, wrist_yaw
  0.0, 0.15, 0.0, 1.2, 0.15, 0.0, 0.0,
  # Right arm (7 joints): shoulder_pitch, shoulder_roll, shoulder_yaw, elbow, wrist_roll, wrist_pitch, wrist_yaw
  0.0, -0.15, 0.0, 1.2, -0.15, 0.0, 0.0,
]
lying_cfg: [
  # Left leg (6 joints)
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  # Right leg (6 joints)
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  # Waist (3 joints)
  0.0, 0.0, 0.0,
  # Left arm (7 joints)
  0.0, 0.15, 0.0, 1.2, 0.15, 0.0, 0.0,
  # Right arm (7 joints)
  0.0, -0.15, 0.0, 1.2, -0.15, 0.0, 0.0,
]
auto_damped_mode: true
motor_enabled: true     # Union[Bool, Tuple[Bool * 29]], the enabled status of each motor in order.
