name: "x30u"
joint_names:
  - "FR_HipX"
  - "FR_HipY"
  - "FR_Knee"
  - "FL_HipX"
  - "FL_HipY"
  - "FL_Knee"
  - "HR_HipX"
  - "HR_HipY"
  - "HR_Knee"
  - "HL_HipX"
  - "HL_HipY"
  - "HL_Knee"
foot_names:
  - "FR_FOOT"
  - "FL_FOOT"
  - "HR_FOOT"
  - "HL_FOOT"
comm_freq: 1000
kp: 400.0
kd: 4.0
standing_cfg: [
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
  0.0, 0.773, -1.501,
]
lying_cfg: [
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
  0.0, 1.221, -2.618,
]
auto_damped_mode: false
kd_damped_mode: 10.0
